apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-inst
        image: eu.gcr.io/opteama-stelia/rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  ports:
    - port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
