apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader-inst
        image: <<CHANGE ME>>
        env:
        - name: BUS_RABBIT
          value: rabbitmq-service
        - name: AUTH_KEYSTONE
          value: keystone-service
        - name: DB_REDIS
          value: redis-service
