apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-inst
        image: eu.gcr.io/opteama-stelia/worker-app
        env:
        - name: BUS_RABBIT
          value: rabbitmq-service
        - name: AUTH_KEYSTONE
          value: keystone-service
